name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.12.0, 10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install imagemin@"^6.0.0"
        npm install uglify-js@"^3.6.0"
        npm install uglifycss@"^0.0.29"
        npm install imagemin-jpegtran
        npm install imagemin-gifsicle@"^6.0.1"
        npm install -g mocha@"^3.5.3"
        npm install chai@"3.5.0" jsonschema@"^1.1.1"
        npm install convert-units@"^2.1.0"
        npm install image-size@"^0.6.3"
        npm install
        bash make build
      env:
        CI: true
